fail when docker fails to start

diff --git a/startdocker b/startdocker
--- a/startdocker
+++ b/startdocker
@@ -4,11 +4,12 @@ set -eu
 
 echo -n starting docker... 
 
-nohup dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 > /dev/null 2>&1 &
+nohup dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375  > nohup.out 2>&1 &
 
 while :
 do 
     docker ps > /dev/null 2>&1 && break || sleep 2
+    ps | grep dockerd > /dev/null || (echo "docker failed to start"; cat nohup.out ; exit 1)
 done
 
 echo DONE 
